// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDez18M3ffPzJr-zgJr4tbt9H7zTKYcvps',
    appId: '1:725353585200:web:0bebb1eafd9a4090ad2bf5',
    messagingSenderId: '725353585200',
    projectId: 'uas-pemrogramanmobile-e4636',
    authDomain: 'uas-pemrogramanmobile-e4636.firebaseapp.com',
    storageBucket: 'uas-pemrogramanmobile-e4636.firebasestorage.app',
    measurementId: 'G-BQN5B0HQFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVba7XUe6JXE2zYDNRRb6ubqiIcq8hR8w',
    appId: '1:725353585200:android:524adb54d3aabc87ad2bf5',
    messagingSenderId: '725353585200',
    projectId: 'uas-pemrogramanmobile-e4636',
    storageBucket: 'uas-pemrogramanmobile-e4636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdnqrrAHtzEMzfsR6c_BpdpNUtKZi1-4',
    appId: '1:725353585200:ios:3a382c36786040afad2bf5',
    messagingSenderId: '725353585200',
    projectId: 'uas-pemrogramanmobile-e4636',
    storageBucket: 'uas-pemrogramanmobile-e4636.firebasestorage.app',
    iosBundleId: 'com.example.sistemPenjurianBurung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdnqrrAHtzEMzfsR6c_BpdpNUtKZi1-4',
    appId: '1:725353585200:ios:3a382c36786040afad2bf5',
    messagingSenderId: '725353585200',
    projectId: 'uas-pemrogramanmobile-e4636',
    storageBucket: 'uas-pemrogramanmobile-e4636.firebasestorage.app',
    iosBundleId: 'com.example.sistemPenjurianBurung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDez18M3ffPzJr-zgJr4tbt9H7zTKYcvps',
    appId: '1:725353585200:web:926c2f44281d66cfad2bf5',
    messagingSenderId: '725353585200',
    projectId: 'uas-pemrogramanmobile-e4636',
    authDomain: 'uas-pemrogramanmobile-e4636.firebaseapp.com',
    storageBucket: 'uas-pemrogramanmobile-e4636.firebasestorage.app',
    measurementId: 'G-GMVS8QE2PY',
  );
}
